import streamlit as st
import sqlite3
import pandas as pd
import datetime
import config

st.set_page_config(page_title="Jetson Daily Brief", layout="centered")

# Hide Streamlit branding
st.markdown("""
<style>
#MainMenu {visibility: hidden;}
footer {visibility: hidden;}
.stApp {margin-top: -80px;}
</style>
""", unsafe_allow_html=True)

def get_data():
    conn = sqlite3.connect(config.DB_NAME)
    # Get today's news
    today = datetime.date.today().isoformat()
    # If testing and no news today, remove the 'WHERE date' clause to see old data
    query = f"SELECT * FROM articles WHERE date = '{today}' ORDER BY impact_score DESC"
    df = pd.read_sql_query(query, conn)
    conn.close()
    return df

st.title("☕ Morning Intelligence")
st.caption(f"Generated by Jetson Orin Nano • {datetime.date.today()}")

try:
    df = get_data()
    
    if df.empty:
        st.info("System is gathering intelligence or no news found for today.")
        st.stop()

    # High Impact Section (Score 7+)
    st.subheader("🔥 Critical Items")
    high_impact = df[df['impact_score'] >= 7]
    
    if high_impact.empty:
        st.write("No critical alerts today.")
    else:
        for _, row in high_impact.iterrows():
            with st.container():
                st.error(f"**{row['title']}**")
                st.write(f"**Why:** {row['impact_reason']}")
                st.write(row['summary'])
                st.markdown(f"[Read Source]({row['link']})")
                st.divider()

    # Low Impact Scrollable
    st.subheader("📰 The Wire")
    low_impact = df[df['impact_score'] < 7]
    
    for _, row in low_impact.iterrows():
        with st.expander(f"{row['impact_score']}/10: {row['title']}"):
            st.caption(row['impact_reason'])
            st.write(row['summary'])
            st.markdown(f"[Read Source]({row['link']})")

except Exception as e:
    st.error(f"Error loading database: {e}")
